[package]
name = "encryptor"
authors = ["shieber"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
encoder = { path = "../encoder"}
hash = { path = "../hash" }
